services:
  app:
    image: ${DOCKERHUB_USERNAME:-user}/exercice-4-testing-battle:${TAG:-latest}
    container_name: api-financiere
    restart: always
    env_file: .env
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3000}
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db:5432/${DB_NAME:-conversion_financiere}
    ports:
      - "${HOST_PORT:-3001}:${PORT:-3000}"
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  db:
    image: "postgres:15-alpine"
    container_name: db-financiere
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-conversion_financiere}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-conversion_financiere}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
